spring.application.name=email-writer-backend
server.port=8080
gemini.api.key=AIzaSyC4SryfbhylEaiY4LqSmTSWY2dUcVbQm7Y

# Enable CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE